language: elixir
elixir:
  - 1.7
  - 1.8
  - 1.9
cache:
    - deps
    - ~/.mix
    - _build
before_script:
  - mix local.hex --force
  - mix do deps.get, deps.compile, compile --warnings-as-errors
script:
  - mix test
  - mix test extra_tests/derive_for_all_of_elixir_test.exs
  - mix credo --strict
